## For a list of some properties that can be overriden go to http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
## The definitive list of properties comes from searching the source code (including Spring source code) for @ConfigurationProperties and @Value annotations, as well as the occasional use of RelaxedEnvironment

##########################################
# Tomcat config
##########################################
server:
  port: ${port:8762}

##########################################
# Spring config
##########################################
spring:
  main:
    show-banner: false

##########################################
# Microservice defaults
##########################################
logging:
  level:
    com.netflix.discovery: OFF
  file: logs/apiproxyserver

log:
  access:
    file:
      directory: logs

authService:
  baseUrl: http://authed1svc.qai.expertcity.com/authentication-service           

service:
    readTimeout: 5000
    connectTimeout: 5000
##########################################
# Zuul config
##########################################
zuul:
#  prefix: api
  stripPrefix: true
  routes:
    sample:
      path: /sample/**
      serviceId: sample
##########################################
# Eureka config
##########################################
eureka:
  password: password # Don't use a default password in a real app
  client:
    enabled: false
    disableDelta: true
    serviceUrl:
      defaultZone: http://user:${eureka.password}@127.0.0.1:8761/eureka/
  instance:
   leaseRenewalIntervalInSeconds: 10
   metadataMap:
     instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}

---
####################################################################################
#
#
#     ED profile
#
#
####################################################################################   
---   
spring:
  profiles: ED
server:
  port: 8080
regdiscovery:
  environment: ${eureka.password:${SECURITY_USER_PASSWORD:password}}  
eureka:
  client:
    enabled: true
    region: ${eureka.region:us-west}
    registerWithEureka: true
    availabilityZones:
      us-west: us-west-1a,us-west-1c
      us-east: us-east-1b,us-east-1c
    serviceUrl:
      us-west-1a: http://user:${regdiscovery.environment}@g2wreged1.acad.expertcity.com:8761/eureka/
      us-west-1c: http://user:${regdiscovery.environment}@g2wreged2.acad.expertcity.com:8761/eureka/
      us-east-1b: http://user:${regdiscovery.environment}@g2wreged1.avad.expertcity.com:8761/eureka/
      us-east-1c: http://user:${regdiscovery.environment}@g2wreged2.avad.expertcity.com:8761/eureka/
authService:
  baseUrl: http://authed1svc.qai.expertcity.com/authentication-service        
####################################################################################
#
#
#     RC profile
#
#
####################################################################################
---
spring:
  profiles: RC
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:${eureka.password}@g2wreged1.acad.expertcity.com:8761/eureka/  
authService:
  baseUrl: http://authed1svc.qai.expertcity.com/authentication-service
####################################################################################
#
#
#     STAGE profile
#
#
####################################################################################
---
spring:
  profiles: STAGE
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:${eureka.password}@g2wreged1.acad.expertcity.com:8761/eureka/    
authService:
  baseUrl: http://authed1svc.qai.expertcity.com/authentication-service  
####################################################################################
#
#
#     LIVE profile
#
#
####################################################################################
---
spring:
  profiles: LIVE
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:${eureka.password}@g2wreged1.acad.expertcity.com:8761/eureka/    
authService:
  baseUrl: http://authed1svc.qai.expertcity.com/authentication-service  
##########################################
# Microservice properties
##########################################     