## For a list of some properties that can be overriden go to http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
## The definitive list of properties comes from searching the source code (including Spring source code) for @ConfigurationProperties and @Value annotations, as well as the occasional use of RelaxedEnvironment

##########################################
# Tomcat config
##########################################
server:
  port: ${port:8080}

##########################################
# Spring config
##########################################
spring:
  main:
    show-banner: false  