## For a list of some properties that can be overriden go to http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
## The definitive list of properties comes from searching the source code (including Spring source code) for @ConfigurationProperties and @Value annotations, as well as the occasional use of RelaxedEnvironment

##########################################
# Tomcat config
##########################################
server:
  port: ${port:8762}

##########################################
# Spring config
##########################################
spring:
  main:
    show-banner: false

##########################################
# Microservice defaults
##########################################
logging:
  level:
    com.netflix.discovery: OFF
  file: logs/apiproxyserver.log

log:
  access:
    file:
      directory: logs

##########################################
# Zuul config
##########################################
zuul:
#  prefix: api
  stripPrefix: true
  routes:
      blueservice:
        path: /blue/**
        serviceId: blueservice
      greenservice:
        path: /green/**
        serviceId: greenservice
      microservice-scaffold:
        path: /g2w/**
        serviceId: apiproxyserver
  route:
      home: /

##########################################
# Eureka config
##########################################
eureka:
  password: password # Don't use a default password in a real app
  client:
    serviceUrl:
      defaultZone: http://user:${eureka.password}@127.0.0.1:8761/eureka/
  instance:
   leaseRenewalIntervalInSeconds: 10
   metadataMap:
     instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}

---
####################################################################################
#
#
#     ED profile
#
#
####################################################################################   
---   
spring:
  profiles: ED
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:${eureka.password}@g2wreged1.acad.expertcity.com:8761/eureka/  
####################################################################################
#
#
#     RC profile
#
#
####################################################################################
---
spring:
  profiles: RC
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:${eureka.password}@g2wreged1.acad.expertcity.com:8761/eureka/  
####################################################################################
#
#
#     STAGE profile
#
#
####################################################################################
---
spring:
  profiles: STAGE
server:
  port: 8080
####################################################################################
#
#
#     LIVE profile
#
#
####################################################################################
---
spring:
  profiles: LIVE
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:${eureka.password}@g2wreged1.acad.expertcity.com:8761/eureka/    
##########################################
# Microservice properties
##########################################     